/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Refillments.java
 *
 * Created on Mar 18, 2012, 11:57:50 AM
 */

package inventorymanagement;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bunny
 */
public class Refillments extends javax.swing.JDialog {

    /** Creates new form Refillments */
    public Refillments(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(inventorymanagement.InventoryManagementApp.class).getContext().getResourceMap(Refillments.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""}
            },
            new String [] {
                "Item Code", "Quantity"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

         
         
        for (int i = 0; i < jTable1.getRowCount(); i++)
            for(int j = 0; j < jTable1.getColumnCount(); j++)
                 jTable1.setValueAt("", i, j);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

       
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       db=new DatabaseAccessor("inventory");
        
        
         String str1,str2;
       
      for ( int i = 0; i < jTable1.getRowCount(); i++){
            
                str1=(String)jTable1.getModel().getValueAt(i,0).toString();
                str2=(String)jTable1.getModel().getValueAt(i,1).toString();

                if(str1.equals("") || str2.equals(""))
                    break;

                ResultSet rs=null;
                double currentQuantity=0;

               
                rs=db.getResultSet("SELECT itemcode, quantity FROM currentinventory");
            try {
                while (rs.next()) {
                    if (rs.getString("itemcode").equals(str1)) {
                        currentQuantity = rs.getDouble("quantity");
                        currentQuantity+=Double.parseDouble(str2);
                        str2=Double.toString(currentQuantity);

                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Refillments.class.getName()).log(Level.SEVERE, null, ex);
            } 
               

               System.out.println(currentQuantity);


                db.updateDb("UPDATE currentinventory SET quantity='"+str2+"', lastupdated='"+db.getDate()+"' WHERE itemcode='"+str1+"'");

                System.out.println(str1+" "+str2);
                //db.execute("INSERT INTO CURRENTINVENTORY(ITEMCODE) VALUES(" + str1 + ")");
                /*try {
                    db.rs = db.statement.executeQuery("INSERT INTO CURRENTINVENTORY(ITEMCODE) VALUES(" + str1 + ")");
                } catch (SQLException ex) {
                    Logger.getLogger(Refillments.class.getName()).log(Level.SEVERE, null, ex);
                 *
                 * "INSERT INTO CURRENTINVENTORY(ITEMCODE) VALUES(" + str1 + ")"
                }*/                  
           
        }


       for ( int i = 0; i < jTable1.getRowCount(); i++)
            for(int j = 0; j < jTable1.getColumnCount(); j++)
                 jTable1.setValueAt("", i, j);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

          

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {


                Refillments dialog = new Refillments(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private DatabaseAccessor db;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
